export const SALES_PRESENTATION_ASSETS = {
  threshold: '/images/clearpath/video/opening-threshold.png',
  fragmented: '/images/clearpath/video/fragmented-operator-day.png',
  platformMap: '/images/clearpath/video/calm-operating-picture.png',
  residentPath: '/images/clearpath/video/resident-workflow-path.png',
  medication: '/images/clearpath/video/medication-guided-logging.png',
  compliance: '/images/clearpath/video/incident-compliance-visibility.png',
  closing: '/images/clearpath/video/closing-confidence-path.png',
  cockpit: '/images/clearpath/clearpath-operational-cockpit.png',
  texture: '/images/clearpath/warm-paper-path-texture.png',
};

export const SALES_PRESENTATION_PLACEHOLDERS = [
  '[FILL: approved differentiators]',
  '[FILL: customer proof]',
  '[FILL: pricing/timeline]',
  '[FILL: implementation model]',
];

export const MAJOR_PLATFORM_MODULES = [
  'dashboard',
  'intake',
  'residents',
  'care-plans',
  'bed-capacity',
  'staff-access',
  'scheduling',
  'medications',
  'inventory',
  'incidents',
  'safety-trends',
  'compliance',
  'documents',
  'chat-handoffs',
  'training',
  'finance',
  'grants',
  'analytics-outcomes',
  'integrations',
  'owner-visibility',
];

export const DIAGNOSTIC_OPTIONS = [
  {
    label: 'Records',
    slideId: 'resident-profiles',
    pain: 'Resident details live in too many places.',
    answer: 'ClearPath centralizes the profile, documents, notes, goals, and next steps.',
  },
  {
    label: 'Meds',
    slideId: 'medications',
    pain: 'Medication support depends on memory and clean handoffs.',
    answer: 'ClearPath organizes medications, dose logs, notes, and inventory context.',
  },
  {
    label: 'Incidents',
    slideId: 'incident-reporting',
    pain: 'The hard moments need better structure than a blank note.',
    answer: 'ClearPath guides the record, follow-up, review, and safety visibility.',
  },
  {
    label: 'Compliance',
    slideId: 'compliance',
    pain: 'Evidence is stressful when it is scattered across folders and staff memory.',
    answer: 'ClearPath connects standards, status, and evidence in one review surface.',
  },
  {
    label: 'Handoffs',
    slideId: 'chat-handoffs',
    pain: 'Shift changes can lose the context that matters most.',
    answer: 'ClearPath gives staff shared channels and task context for follow-through.',
  },
  {
    label: 'Owner view',
    slideId: 'dashboard',
    pain: 'Operators need to know what needs attention without asking everyone first.',
    answer: 'ClearPath makes the day visible from one operating dashboard.',
  },
];

export const SALES_PRESENTATION_SLIDES = [
  {
    id: 'opening-path',
    eyebrow: 'ClearPath',
    headline: 'Run the residence from one connected operating path.',
    salesCopy:
      'ClearPath brings the daily work of recovery housing into one calm place: residents, staff, beds, medications, incidents, documents, compliance, communication, and owner visibility.',
    painPoint: 'Operators carry mission-critical work across too many tools, notes, folders, and conversations.',
    clearPathAnswer: 'ClearPath organizes the work around the people and decisions operators already manage every day.',
    presenterNote: 'Open with the operator’s world, not the product menu. The promise is clarity across daily operations.',
    interactionCue: 'Start the story, then move directly into the pressure diagnostic.',
    modules: ['owner-visibility'],
    visual: SALES_PRESENTATION_ASSETS.threshold,
    route: '/presentation',
    accent: '#D58A38',
  },
  {
    id: 'scattered-day',
    eyebrow: 'Operator Reality',
    headline: 'The real problem is not effort. It is scattered work.',
    salesCopy:
      'Most operators are already doing the right work. ClearPath helps make that work easier to see, easier to document, and easier to hand off.',
    painPoint: 'Records, texts, binders, spreadsheets, and staff memory make the day harder to trust.',
    clearPathAnswer: 'ClearPath turns scattered updates into structured operating context.',
    presenterNote: 'This slide should create recognition: the prospect should feel understood before they are sold to.',
    interactionCue: 'Ask: Where does this scatter show up most often for your team?',
    modules: ['dashboard', 'owner-visibility'],
    visual: SALES_PRESENTATION_ASSETS.fragmented,
    route: '/presentation',
    accent: '#8DAA75',
  },
  {
    id: 'diagnostic',
    eyebrow: 'Operator Diagnostic',
    headline: 'Where does the pressure show up first?',
    salesCopy:
      'Every residence has a different pressure point. ClearPath lets the sales conversation start with the operator’s reality, then connect that pressure to the right workflow.',
    painPoint: 'A feature tour can miss the workflow that matters most to the buyer.',
    clearPathAnswer: 'The diagnostic routes the conversation to the area that is costing the team the most attention.',
    presenterNote: 'Use this as a live conversation moment. Pick the operator’s pain, then jump to the matching module.',
    interactionCue: 'Click a pressure area to jump to its sales slide.',
    modules: MAJOR_PLATFORM_MODULES,
    visual: SALES_PRESENTATION_ASSETS.platformMap,
    diagnostic: true,
    route: '/presentation',
    accent: '#D4AF37',
  },
  {
    id: 'platform-map',
    eyebrow: 'Platform Map',
    headline: 'ClearPath connects the operating system behind the house.',
    salesCopy:
      'The platform is not a pile of separate modules. It is a connected operating layer across residents, staff, beds, safety, documents, finances, outcomes, and leadership review.',
    painPoint: 'Disconnected software forces operators to rebuild the same story in every tool.',
    clearPathAnswer: 'ClearPath uses shared records and connected workflows so each module strengthens the next one.',
    presenterNote: 'Position the platform as a system. Each workflow should feel connected to resident care and owner visibility.',
    interactionCue: 'Use module jump controls to move from the map into a specific workflow.',
    modules: MAJOR_PLATFORM_MODULES,
    visual: SALES_PRESENTATION_ASSETS.platformMap,
    route: '/presentation',
    accent: '#D58A38',
  },
  {
    id: 'dashboard',
    eyebrow: 'Owner Visibility',
    headline: 'Start each day with the operating picture.',
    salesCopy:
      'The dashboard gives operators a place to see what needs attention: residents, occupancy, incidents, medication activity, compliance status, inventory, and open work.',
    painPoint: 'Owners and directors should not have to ask every staff member for the status of the day.',
    clearPathAnswer: 'ClearPath makes the day visible so leaders can review, prioritize, and follow up.',
    presenterNote: 'Keep this practical: the dashboard is the daily command surface, not a vanity analytics page.',
    interactionCue: 'Point to the dashboard as the hub that every workflow feeds.',
    modules: ['dashboard', 'owner-visibility'],
    visual: SALES_PRESENTATION_ASSETS.cockpit,
    route: '/',
    accent: '#D58A38',
  },
  {
    id: 'intake',
    eyebrow: 'Intake',
    headline: 'Turn an applicant into an organized resident record.',
    salesCopy:
      'ClearPath supports the intake path from application details to resident profile, documents, contacts, and the first operational steps staff need to know.',
    painPoint: 'Paper intake and scattered uploads can create gaps before a resident even moves in.',
    clearPathAnswer: 'ClearPath creates a cleaner intake-to-profile handoff for staff and leadership.',
    presenterNote: 'Do not overclaim automation. Sell the handoff: application information becomes usable operating context.',
    interactionCue: 'Route from intake into resident profile to show continuity.',
    modules: ['intake', 'residents', 'documents'],
    visual: SALES_PRESENTATION_ASSETS.residentPath,
    route: '/intake',
    accent: '#B8704D',
  },
  {
    id: 'resident-profiles',
    eyebrow: 'Resident Profiles',
    headline: 'Give staff one place to understand the resident story.',
    salesCopy:
      'Resident profiles bring together status, location, phase, alerts, notes, documents, contacts, medication context, milestones, and timeline activity.',
    painPoint: 'When resident context is split across tools, staff lose time reconstructing the story.',
    clearPathAnswer: 'ClearPath gives staff a resident-centered view for daily support and review.',
    presenterNote: 'Speak to trust: the profile is where the team aligns around what is true and what comes next.',
    interactionCue: 'Jump to care plans, documents, or medications from the resident story.',
    modules: ['residents', 'documents', 'medications'],
    visual: SALES_PRESENTATION_ASSETS.residentPath,
    route: '/residents',
    accent: '#B8704D',
  },
  {
    id: 'care-plans',
    eyebrow: 'Resident Progress',
    headline: 'Move goals, tasks, and milestones out of staff memory.',
    salesCopy:
      'ClearPath gives operators a place to organize care plan goals, resident tasks, recovery milestones, notes, and follow-up context.',
    painPoint: 'Progress is hard to support when goals and next steps are informal or spread across conversations.',
    clearPathAnswer: 'ClearPath helps make the resident path visible enough for staff to review and support.',
    presenterNote: 'Frame this as operational follow-through, not clinical treatment software.',
    interactionCue: 'Connect resident progress back to team handoffs and outcomes.',
    modules: ['care-plans', 'residents', 'analytics-outcomes'],
    visual: SALES_PRESENTATION_ASSETS.residentPath,
    route: '/residents',
    accent: '#8DAA75',
  },
  {
    id: 'bed-capacity',
    eyebrow: 'Beds & Occupancy',
    headline: 'Know where capacity stands before decisions get urgent.',
    salesCopy:
      'ClearPath helps operators review locations, bed assignments, applicants, occupancy, and placement decisions from a shared operating surface.',
    painPoint: 'Capacity decisions get messy when beds, rooms, applicants, and resident status are tracked separately.',
    clearPathAnswer: 'ClearPath gives bed capacity a visible workflow connected to residents and locations.',
    presenterNote: 'Tie occupancy to real operator decisions: placement, waitlist pressure, staffing, and reporting.',
    interactionCue: 'Show how capacity connects to intake and resident status.',
    modules: ['bed-capacity', 'intake', 'residents'],
    visual: SALES_PRESENTATION_ASSETS.cockpit,
    route: '/bed-capacity',
    accent: '#D4AF37',
  },
  {
    id: 'staff-access',
    eyebrow: 'Staff & Access',
    headline: 'Give every role the context it needs.',
    salesCopy:
      'ClearPath supports staff records, organization membership, role-aware access, and the operating context each team member needs to do their part.',
    painPoint: 'As teams grow, access and responsibility can become unclear.',
    clearPathAnswer: 'ClearPath helps operators organize staff roles and connect people to the workflows they own.',
    presenterNote: 'Keep access claims conservative. Say role-aware, not compliance-complete.',
    interactionCue: 'Connect staff access to handoffs, audit context, and owner visibility.',
    modules: ['staff-access', 'owner-visibility'],
    visual: SALES_PRESENTATION_ASSETS.platformMap,
    route: '/staff',
    accent: '#8DAA75',
  },
  {
    id: 'scheduling',
    eyebrow: 'Scheduling',
    headline: 'Make shift coverage easier to see and manage.',
    salesCopy:
      'ClearPath supports staff scheduling so operators can review who is assigned, where coverage sits, and how shifts connect to daily responsibilities.',
    painPoint: 'Coverage questions become operational risk when schedules live outside the rest of the system.',
    clearPathAnswer: 'ClearPath brings scheduling closer to residents, locations, tasks, and handoffs.',
    presenterNote: 'Sell scheduling as a visibility layer that supports daily rhythm.',
    interactionCue: 'Move from scheduling into handoff and staff task context.',
    modules: ['scheduling', 'staff-access', 'chat-handoffs'],
    visual: SALES_PRESENTATION_ASSETS.platformMap,
    route: '/scheduling',
    accent: '#D58A38',
  },
  {
    id: 'medications',
    eyebrow: 'Medication Support',
    headline: 'Medication work needs a guided record, not guesswork.',
    salesCopy:
      'ClearPath organizes medications, dose logs, medication notes, inventory context, and staff review moments in one operating flow.',
    painPoint: 'Medication support becomes fragile when logs, notes, and supply context are disconnected.',
    clearPathAnswer: 'ClearPath helps staff document medication activity and review what needs follow-up.',
    presenterNote: 'Avoid clinical claims. Sell consistency, visibility, and handoff quality.',
    interactionCue: 'Use the movie or workflow slide to show logging as a calm guided moment.',
    modules: ['medications', 'inventory', 'residents'],
    visual: SALES_PRESENTATION_ASSETS.medication,
    route: '/residents',
    accent: '#6F8C69',
  },
  {
    id: 'inventory',
    eyebrow: 'Inventory',
    headline: 'Supplies and requests belong in the same operating picture.',
    salesCopy:
      'ClearPath supports inventory items, supply requests, medication-related stock context, and location-level review for operators.',
    painPoint: 'House supplies and medication-adjacent inventory can become invisible until something is missing.',
    clearPathAnswer: 'ClearPath helps staff request, review, and update inventory where operators can see it.',
    presenterNote: 'Connect inventory to safety, daily operations, and cost awareness.',
    interactionCue: 'Route from inventory into finance or medication support.',
    modules: ['inventory', 'medications', 'finance'],
    visual: SALES_PRESENTATION_ASSETS.medication,
    route: '/inventory',
    accent: '#D4AF37',
  },
  {
    id: 'incident-reporting',
    eyebrow: 'Incidents',
    headline: 'The hardest moments deserve structure.',
    salesCopy:
      'ClearPath gives teams a structured place to document incidents, severity, location, resident context, follow-up, and review status.',
    painPoint: 'A blank note can leave too much room for missing details when the situation is already stressful.',
    clearPathAnswer: 'ClearPath helps staff create a clearer incident record and keep follow-up visible.',
    presenterNote: 'Lead with operator relief: structure helps the team remember what matters.',
    interactionCue: 'Follow this slide with safety trends to show leadership visibility.',
    modules: ['incidents', 'safety-trends', 'residents'],
    visual: SALES_PRESENTATION_ASSETS.compliance,
    route: '/incidents',
    accent: '#C56A3A',
  },
  {
    id: 'safety-trends',
    eyebrow: 'Safety Patterns',
    headline: 'Incidents become more useful when patterns are visible.',
    salesCopy:
      'ClearPath supports incident review and safety pattern visibility so operators can look across locations, categories, severity, and timing.',
    painPoint: 'When incidents only live as isolated reports, leadership can miss patterns that deserve attention.',
    clearPathAnswer: 'ClearPath helps turn incident records into reviewable safety context.',
    presenterNote: 'Keep this as visibility, not prediction. The value is pattern review and better operational questions.',
    interactionCue: 'Connect safety trends to staff training and compliance evidence.',
    modules: ['safety-trends', 'incidents', 'training'],
    visual: SALES_PRESENTATION_ASSETS.compliance,
    route: '/incident-safety',
    accent: '#C56A3A',
  },
  {
    id: 'compliance',
    eyebrow: 'Compliance Readiness',
    headline: 'Make evidence easier to find before it is needed.',
    salesCopy:
      'ClearPath organizes compliance items, standards, status, and evidence attachments so operators can review readiness without rebuilding the file from scratch.',
    painPoint: 'Compliance stress grows when evidence is scattered across folders, staff computers, and memory.',
    clearPathAnswer: 'ClearPath creates a clearer place to track standards, status, and supporting evidence.',
    presenterNote: 'Use readiness language, not promises. The product supports organization and review.',
    interactionCue: 'Show the link between compliance evidence, secure documents, and staff training.',
    modules: ['compliance', 'documents', 'training'],
    visual: SALES_PRESENTATION_ASSETS.compliance,
    route: '/compliance',
    accent: '#D58A38',
  },
  {
    id: 'documents',
    eyebrow: 'Documents & Signatures',
    headline: 'Keep important documents connected to the resident and the house.',
    salesCopy:
      'ClearPath supports resident documents, secure documents, document categories, upload workflows, and signature requests for key acknowledgments.',
    painPoint: 'Documents lose value when staff cannot quickly tell what exists, what is missing, and who it belongs to.',
    clearPathAnswer: 'ClearPath connects documents to residents, policies, evidence, and review workflows.',
    presenterNote: 'Make this concrete: agreements, IDs, policies, evidence, and signed acknowledgments.',
    interactionCue: 'Route to compliance or resident profiles after this slide.',
    modules: ['documents', 'compliance', 'residents'],
    visual: SALES_PRESENTATION_ASSETS.residentPath,
    route: '/secure-docs',
    accent: '#8DAA75',
  },
  {
    id: 'chat-handoffs',
    eyebrow: 'Communication',
    headline: 'Handoffs need shared context, not private memory.',
    salesCopy:
      'ClearPath gives teams a place for role-aware communication, house channels, community updates, and direct context around daily operations.',
    painPoint: 'Important updates can disappear into personal texts or conversations that not everyone can see.',
    clearPathAnswer: 'ClearPath keeps communication closer to the operating work it affects.',
    presenterNote: 'The sales point is accountability and continuity, not simply “chat.”',
    interactionCue: 'Ask how the team currently handles shift-change updates.',
    modules: ['chat-handoffs', 'staff-access', 'scheduling'],
    visual: SALES_PRESENTATION_ASSETS.platformMap,
    route: '/chat',
    accent: '#D4AF37',
  },
  {
    id: 'training',
    eyebrow: 'Training',
    headline: 'Training should live where the work happens.',
    salesCopy:
      'ClearPath supports training modules and completions so operators can connect staff development to the same system that holds daily operations.',
    painPoint: 'Training records are easy to lose when they live outside the team’s operating system.',
    clearPathAnswer: 'ClearPath helps staff learning, completion review, and operational readiness stay connected.',
    presenterNote: 'Connect training to incidents, compliance, onboarding, and consistent operations.',
    interactionCue: 'Route from training to safety trends or compliance evidence.',
    modules: ['training', 'compliance', 'safety-trends'],
    visual: SALES_PRESENTATION_ASSETS.compliance,
    route: '/training',
    accent: '#C56A3A',
  },
  {
    id: 'finance',
    eyebrow: 'Finance',
    headline: 'Give operating costs a clearer home.',
    salesCopy:
      'ClearPath supports location expenses, categories, recurring costs, vendors, and budget review context for operators managing houses and programs.',
    painPoint: 'Operational spending can become disconnected from occupancy, grants, inventory, and house-level needs.',
    clearPathAnswer: 'ClearPath helps operators review expenses in the same environment as the work that creates them.',
    presenterNote: 'Keep this grounded in visibility and stewardship, not accounting replacement.',
    interactionCue: 'Connect finance to grants, inventory, and owner review.',
    modules: ['finance', 'inventory', 'grants'],
    visual: SALES_PRESENTATION_ASSETS.cockpit,
    route: '/finance',
    accent: '#8DAA75',
  },
  {
    id: 'grants',
    eyebrow: 'Grants',
    headline: 'Grant work needs both people context and reporting context.',
    salesCopy:
      'ClearPath supports grants, enrollments, required metrics context, resident linkage, and reporting preparation surfaces.',
    painPoint: 'Grant reporting becomes harder when funder requirements are separate from resident and program records.',
    clearPathAnswer: 'ClearPath helps connect grant records to residents, locations, outcomes, and review needs.',
    presenterNote: 'Use placeholder proof for funder-specific metrics until approved.',
    interactionCue: 'Route from grants into outcomes and analytics.',
    modules: ['grants', 'analytics-outcomes', 'residents'],
    visual: SALES_PRESENTATION_ASSETS.cockpit,
    route: '/grants',
    accent: '#D58A38',
  },
  {
    id: 'analytics-outcomes',
    eyebrow: 'Outcomes & Impact',
    headline: 'Reporting gets stronger when daily work is already organized.',
    salesCopy:
      'ClearPath supports analytics and outcomes views that help operators review occupancy, resident progress, incidents, finance, grants, and impact context.',
    painPoint: 'Reporting is harder when the underlying records are scattered or incomplete.',
    clearPathAnswer: 'ClearPath helps operators turn daily records into clearer review and reporting conversations.',
    presenterNote: 'Do not invent outcome numbers. Use this as a reporting readiness and review slide.',
    interactionCue: 'Name the proof still needed: [FILL: approved proof source].',
    modules: ['analytics-outcomes', 'grants', 'finance', 'owner-visibility'],
    visual: SALES_PRESENTATION_ASSETS.cockpit,
    route: '/analytics',
    accent: '#D4AF37',
  },
  {
    id: 'integrations-owned-product',
    eyebrow: 'Connections & Ownership',
    headline: 'ClearPath is being shaped as owned operating software, not another disconnected workaround.',
    salesCopy:
      'ClearPath includes connection points for integrations and a product direction centered on the operator’s real workflows. [FILL: approved differentiators]',
    painPoint: 'Operators need clarity on what is built, what connects, what is planned, and what the implementation path looks like.',
    clearPathAnswer:
      'ClearPath gives the product conversation a clear structure: current workflows, integration needs, implementation model, and next validation step.',
    presenterNote: 'Use this to explain owned-product clarity without overstating maturity or integrations.',
    interactionCue: 'Name required integrations, then mark them as validation items.',
    modules: ['integrations', 'owner-visibility'],
    visual: SALES_PRESENTATION_ASSETS.platformMap,
    route: '/integrations',
    accent: '#8DAA75',
  },
  {
    id: 'close-validation',
    eyebrow: 'Next Step',
    headline: 'Choose the first workflow and validate it with a real operator day.',
    salesCopy:
      'The best next step is not a bigger feature list. It is choosing the first workflow to test: intake, resident profile, medications, incidents, compliance, handoffs, or owner dashboard.',
    painPoint: 'A buyer can like the platform and still need a clear, low-risk next step.',
    clearPathAnswer:
      'ClearPath closes with a practical validation path: pick the workflow, load realistic records, present the day, and define what proof is needed next. [FILL: pricing/timeline] [FILL: implementation model]',
    presenterNote: 'Close by asking for a workflow decision, not abstract enthusiasm.',
    interactionCue: 'Ask: Which workflow should we validate first with your team?',
    modules: MAJOR_PLATFORM_MODULES,
    visual: SALES_PRESENTATION_ASSETS.closing,
    route: '/presentation',
    accent: '#D58A38',
  },
];

export const SALES_PRESENTATION_VIDEO_SCENES = [
  {
    id: 'film-opening',
    sourceSlideId: 'opening-path',
    title: 'One connected path',
    caption: 'ClearPath brings daily recovery residence operations into one operating path.',
    narration:
      'ClearPath is built around a simple operator truth: the work is already happening. The question is whether the team can see it, trust it, and hand it off clearly.',
    asset: SALES_PRESENTATION_ASSETS.threshold,
    accent: '#D58A38',
    durationInFrames: 390,
  },
  {
    id: 'film-scatter',
    sourceSlideId: 'scattered-day',
    title: 'The work starts scattered',
    caption: 'Records, messages, files, and follow-up all compete for attention.',
    narration:
      'In many recovery residences, the day starts across texts, paper, folders, spreadsheets, and memory. ClearPath helps bring those threads into an operating picture.',
    asset: SALES_PRESENTATION_ASSETS.fragmented,
    accent: '#8DAA75',
    durationInFrames: 390,
  },
  {
    id: 'film-map',
    sourceSlideId: 'platform-map',
    title: 'A platform map for the house',
    caption: 'Residents, staff, beds, safety, documents, finance, outcomes, and owner review stay connected.',
    narration:
      'Instead of touring disconnected features, ClearPath tells one system story: resident operations, team accountability, safety, documentation, reporting, and leadership visibility.',
    asset: SALES_PRESENTATION_ASSETS.platformMap,
    accent: '#D4AF37',
    durationInFrames: 450,
  },
  {
    id: 'film-dashboard',
    sourceSlideId: 'dashboard',
    title: 'Today’s operating picture',
    caption: 'The dashboard becomes the place to see what needs attention.',
    narration:
      'The dashboard gives operators a daily starting point. It brings attention to residents, occupancy, incidents, medication activity, compliance status, inventory, and open work.',
    asset: SALES_PRESENTATION_ASSETS.cockpit,
    accent: '#D58A38',
    durationInFrames: 420,
  },
  {
    id: 'film-residents',
    sourceSlideId: 'resident-profiles',
    title: 'Resident context in one place',
    caption: 'Profiles connect status, documents, notes, contacts, milestones, and next steps.',
    narration:
      'Resident profiles make the work more coherent. Staff can review context, documents, alerts, notes, care goals, and timeline activity without rebuilding the resident story each time.',
    asset: SALES_PRESENTATION_ASSETS.residentPath,
    accent: '#B8704D',
    durationInFrames: 450,
  },
  {
    id: 'film-capacity-staff',
    sourceSlideId: 'bed-capacity',
    title: 'Capacity, staff, and coverage',
    caption: 'Beds, locations, roles, and schedules become part of the same operating rhythm.',
    narration:
      'ClearPath also supports the structure around the resident: bed capacity, locations, staff roles, and scheduling. Operators can connect people, places, and coverage in one daily rhythm.',
    asset: SALES_PRESENTATION_ASSETS.platformMap,
    accent: '#D4AF37',
    durationInFrames: 390,
  },
  {
    id: 'film-meds-inventory',
    sourceSlideId: 'medications',
    title: 'Medication and inventory visibility',
    caption: 'Medication support and supply requests stay closer to the resident workflow.',
    narration:
      'Medication tracking, dose logs, notes, and inventory context are places where small misses can become stressful. ClearPath helps staff document the moment and keep follow-up visible.',
    asset: SALES_PRESENTATION_ASSETS.medication,
    accent: '#6F8C69',
    durationInFrames: 420,
  },
  {
    id: 'film-safety',
    sourceSlideId: 'incident-reporting',
    title: 'Incidents with structure',
    caption: 'Hard moments become clearer records, follow-up, and safety review.',
    narration:
      'When an incident happens, the team needs structure. ClearPath supports the record, the follow-up, the resident context, and the review surface leaders need afterward.',
    asset: SALES_PRESENTATION_ASSETS.compliance,
    accent: '#C56A3A',
    durationInFrames: 420,
  },
  {
    id: 'film-compliance-docs',
    sourceSlideId: 'compliance',
    title: 'Evidence without the scramble',
    caption: 'Compliance, documents, signatures, and training stay easier to review.',
    narration:
      'Compliance readiness gets calmer when evidence is organized before it is needed. ClearPath connects standards, documents, signatures, staff training, and review context.',
    asset: SALES_PRESENTATION_ASSETS.compliance,
    accent: '#D58A38',
    durationInFrames: 420,
  },
  {
    id: 'film-reporting',
    sourceSlideId: 'analytics-outcomes',
    title: 'Reporting starts with daily records',
    caption: 'Finance, grants, outcomes, and analytics become stronger when the work is already organized.',
    narration:
      'Finance, grants, outcomes, and analytics all depend on the same foundation: clean daily records. ClearPath helps operators prepare stronger reporting conversations from the work they already do.',
    asset: SALES_PRESENTATION_ASSETS.cockpit,
    accent: '#D4AF37',
    durationInFrames: 420,
  },
  {
    id: 'film-close',
    sourceSlideId: 'close-validation',
    title: 'Choose the first workflow',
    caption: 'Pick one operator workflow and validate it with a real day.',
    narration:
      'The next step is practical. Choose the first workflow to validate, load realistic records, walk through the operator day, and decide what proof the team needs next.',
    asset: SALES_PRESENTATION_ASSETS.closing,
    accent: '#D58A38',
    durationInFrames: 390,
  },
];

export const FEATURE_CLAIMS = MAJOR_PLATFORM_MODULES.map((module) => ({
  module,
  claim: 'Supports an operator-visible workflow already represented in the ClearPath application surface.',
}));

export const SALES_PRESENTATION_TOTAL_VIDEO_FRAMES = SALES_PRESENTATION_VIDEO_SCENES.reduce(
  (total, scene) => total + scene.durationInFrames,
  0
);

export const SALES_PRESENTATION_VOICEOVER = SALES_PRESENTATION_VIDEO_SCENES.map((scene) => scene.narration).join('\n\n');

export function getSlideById(id) {
  return SALES_PRESENTATION_SLIDES.find((slide) => slide.id === id);
}
